"""
agents/qa.py
------------
Agent 4 — QAAgent

Responsibility:
  Deterministic, rule-based quality gate applied to every qualified lead
  that has copy generated by CopywriterAgent. Zero LLM calls — pure Python.

Checks performed:
  1. LinkedIn invite length   — must be ≤ 300 characters (platform hard limit)
  2. Generic phrases          — blocked list of sales clichés (invite + email)
  3. Company name mention     — invite must reference the company
  4. YotamCo mention         — invite must contain "yotamco"
  5. Email subject exists     — subject must be ≥ 5 characters
  6. Email body length        — body must be ≥ 100 characters

A lead's qa_passed flag is set to True only if ALL checks pass.
Failing leads are kept in the pipeline; the reporter surfaces their issues.
"""

from models.lead import Lead
from utils.logging import make_logger


# ── Blocked phrases ───────────────────────────────────────────────────────────

GENERIC_PHRASES: list[str] = [
    "i hope this finds you well",
    "i wanted to reach out",
    "touch base",
    "synergy",
    "leverage",
    "game-changer",
    "revolutionize",
    "quick call",
    "pick your brain",
    "circle back",
    "per my last email",
    "as per",
    "hope you're doing well",
    "i came across your profile",
]


# ── Agent ─────────────────────────────────────────────────────────────────────

class QAAgent:
    """
    Quality gate that selects the best copy variant for each lead.

    For leads with multiple variants (generated by CopywriterAgent):
      1. Score every variant using a deterministic rubric.
      2. Pick the highest-scoring variant that passes all checks.
         If none pass, pick the one with fewest issues.
      3. Apply the winning variant to the lead's copy fields.

    Then run the standard checks on the selected variant to set qa_passed/qa_issues.
    """

    log = make_logger("QAAgent")
    LINKEDIN_CHAR_LIMIT = 300
    EMAIL_BODY_MIN_LEN  = 100
    EMAIL_SUBJECT_MIN   = 5

    # ── Public API ────────────────────────────────────────────────────────────

    def run(self, leads: list[Lead]) -> list[Lead]:
        candidates = [l for l in leads if not l.disqualified and l.linkedin_invite]
        self.log.info(f"▶  Running QA on {len(candidates)} leads...")

        passed = failed = 0
        for lead in candidates:
            if len(lead.copy_variants) > 1:
                self._select_best_variant(lead)
            self._check(lead)
            if lead.qa_passed:
                passed += 1
            else:
                failed += 1

        self.log.info(f"   ✅ QA passed: {passed}  ⚠️  QA failed: {failed}")
        return leads

    # ── Variant selection ─────────────────────────────────────────────────────

    def _select_best_variant(self, lead: Lead) -> None:
        """Score all variants and apply the best one to the lead's copy fields."""
        variants = lead.copy_variants
        ranked = []
        for i, v in enumerate(variants):
            issues = self._variant_issues(v, lead)
            score  = self._score_variant(v, lead)
            ranked.append((len(issues), -score, i, v))

        ranked.sort()  # fewest issues first, then highest score
        best_issue_count, best_neg_score, best_idx, best = ranked[0]

        lead.linkedin_invite         = best["linkedin_invite"]
        lead.follow_up_email_subject = best["follow_up_email_subject"]
        lead.follow_up_email_body    = best["follow_up_email_body"]
        lead.qa_selected_variant     = best_idx + 1

        scores_str = "  |  ".join(
            f"V{r[2]+1}: score={-r[1]}, issues={r[0]}" for r in ranked
        )
        self.log.info(
            f"   🎯 {lead.name}: variant {best_idx + 1}/{len(variants)} selected  "
            f"[{scores_str}]"
        )

    def _score_variant(self, variant: dict, lead: Lead) -> int:
        """
        Higher score = better variant. Scoring rubric:
          +4  invite length efficiency (proportional to 300-char limit)
          +2  company name in invite
          +2  YotamCo mentioned in invite
          +1  email subject exists and is long enough
          +1  email body meets minimum length
          -2  per blocked phrase hit (invite or email)
        """
        invite     = variant.get("linkedin_invite", "")
        subject    = variant.get("follow_up_email_subject", "")
        body       = variant.get("follow_up_email_body", "")
        invite_low = invite.lower()
        body_low   = body.lower()

        score = 0

        # Reward invite content density up to the char limit
        if len(invite) <= self.LINKEDIN_CHAR_LIMIT:
            score += int((len(invite) / self.LINKEDIN_CHAR_LIMIT) * 4)

        # Company name present
        words = lead.company_name.split()
        if lead.company_name.lower() in invite_low or (
            words and words[0].lower() in invite_low
        ):
            score += 2

        # YotamCo mentioned
        if "yotamco" in invite_low:
            score += 2

        # Email subject quality
        if subject and len(subject) >= self.EMAIL_SUBJECT_MIN:
            score += 1

        # Email body length
        if len(body) >= self.EMAIL_BODY_MIN_LEN:
            score += 1

        # Penalise blocked phrases
        for phrase in GENERIC_PHRASES:
            if phrase in invite_low:
                score -= 2
            if phrase in body_low:
                score -= 2

        return score

    def _variant_issues(self, variant: dict, lead: Lead) -> list[str]:
        """Return the list of QA issues for a variant dict without mutating the lead."""
        invite     = variant.get("linkedin_invite", "")
        body       = variant.get("follow_up_email_body", "")
        subject    = variant.get("follow_up_email_subject", "")
        invite_low = invite.lower()
        body_low   = body.lower()
        issues: list[str] = []

        if len(invite) > self.LINKEDIN_CHAR_LIMIT:
            issues.append(f"invite too long ({len(invite)} chars)")

        for phrase in GENERIC_PHRASES:
            if phrase in invite_low:
                issues.append(f"blocked phrase in invite: '{phrase}'")
            if phrase in body_low:
                issues.append(f"blocked phrase in email: '{phrase}'")

        words = lead.company_name.split()
        if lead.company_name.lower() not in invite_low and not (
            words and words[0].lower() in invite_low
        ):
            issues.append("company name missing from invite")

        if "yotamco" not in invite_low:
            issues.append("YotamCo not mentioned in invite")

        if not subject or len(subject) < self.EMAIL_SUBJECT_MIN:
            issues.append("email subject missing or too short")

        if len(body) < self.EMAIL_BODY_MIN_LEN:
            issues.append(f"email body too short ({len(body)} chars)")

        return issues

    # ── Final check on selected variant ──────────────────────────────────────

    def _check(self, lead: Lead) -> None:
        issues: list[str] = []
        invite      = lead.linkedin_invite
        email_body  = lead.follow_up_email_body
        invite_low  = invite.lower()
        email_low   = email_body.lower()

        if len(invite) > self.LINKEDIN_CHAR_LIMIT:
            issues.append(
                f"LinkedIn invite too long: {len(invite)} chars (limit {self.LINKEDIN_CHAR_LIMIT})"
            )

        for phrase in GENERIC_PHRASES:
            if phrase in invite_low:
                issues.append(f"Generic phrase in LinkedIn invite: '{phrase}'")
            if phrase in email_low:
                issues.append(f"Generic phrase in email body: '{phrase}'")

        name_words = lead.company_name.split()
        company_first_word = name_words[0].lower() if name_words else ""
        if (
            lead.company_name.lower() not in invite_low
            and (not company_first_word or company_first_word not in invite_low)
        ):
            issues.append("LinkedIn invite does not mention the company name")

        if "yotamco" not in invite_low:
            issues.append("LinkedIn invite doesn't mention YotamCo")

        if not lead.follow_up_email_subject or len(lead.follow_up_email_subject) < self.EMAIL_SUBJECT_MIN:
            issues.append("Email subject is missing or too short")

        if len(email_body) < self.EMAIL_BODY_MIN_LEN:
            issues.append(f"Email body too short ({len(email_body)} chars, min {self.EMAIL_BODY_MIN_LEN})")

        lead.qa_issues = issues
        lead.qa_passed = len(issues) == 0

        if issues:
            self.log.warning(
                f"   ⚠️  {lead.name}: {len(issues)} issue(s) — {'; '.join(issues)}"
            )
        else:
            self.log.info(f"   ✅ {lead.name}: QA passed")
