"""
agents/qa.py
------------
Agent 4 — QAAgent

Responsibility:
  Deterministic, rule-based quality gate applied to every qualified lead
  that has copy generated by CopywriterAgent. Zero LLM calls — pure Python.

Checks performed:
  1. LinkedIn invite length   — must be ≤ 300 characters (platform hard limit)
  2. Generic phrases          — blocked list of sales clichés (invite + email)
  3. Company name mention     — invite must reference the company
  4. ScyllaDB mention         — invite must contain "scylladb" or "scylla"
  5. Email subject exists     — subject must be ≥ 5 characters
  6. Email body length        — body must be ≥ 100 characters

A lead's qa_passed flag is set to True only if ALL checks pass.
Failing leads are kept in the pipeline; the reporter surfaces their issues.
"""

from models.lead import Lead
from utils.logging import make_logger


# ── Blocked phrases ───────────────────────────────────────────────────────────

GENERIC_PHRASES: list[str] = [
    "i hope this finds you well",
    "i wanted to reach out",
    "touch base",
    "synergy",
    "leverage",
    "game-changer",
    "revolutionize",
    "quick call",
    "pick your brain",
    "circle back",
    "per my last email",
    "as per",
    "hope you're doing well",
    "i came across your profile",
]


# ── Agent ─────────────────────────────────────────────────────────────────────

class QAAgent:
    """Pure-rule quality gate; mutates lead.qa_passed and lead.qa_issues."""

    log = make_logger("QAAgent")
    LINKEDIN_CHAR_LIMIT = 300
    EMAIL_BODY_MIN_LEN  = 100
    EMAIL_SUBJECT_MIN   = 5

    # ── Public API ────────────────────────────────────────────────────────────

    def run(self, leads: list[Lead]) -> list[Lead]:
        candidates = [l for l in leads if not l.disqualified and l.linkedin_invite]
        self.log.info(f"▶  Running QA on {len(candidates)} leads...")

        passed = failed = 0
        for lead in candidates:
            self._check(lead)
            if lead.qa_passed:
                passed += 1
            else:
                failed += 1

        self.log.info(f"   ✅ QA passed: {passed}  ⚠️  QA failed: {failed}")
        return leads

    # ── Private helpers ───────────────────────────────────────────────────────

    def _check(self, lead: Lead) -> None:
        issues: list[str] = []
        invite      = lead.linkedin_invite
        email_body  = lead.follow_up_email_body
        invite_low  = invite.lower()
        email_low   = email_body.lower()

        # 1. LinkedIn character limit
        if len(invite) > self.LINKEDIN_CHAR_LIMIT:
            issues.append(
                f"LinkedIn invite too long: {len(invite)} chars (limit {self.LINKEDIN_CHAR_LIMIT})"
            )

        # 2. Generic / cliché phrases — checked in both messages
        for phrase in GENERIC_PHRASES:
            if phrase in invite_low:
                issues.append(f"Generic phrase in LinkedIn invite: '{phrase}'")
            if phrase in email_low:
                issues.append(f"Generic phrase in email body: '{phrase}'")

        # 3. Company name must appear in invite
        name_words = lead.company_name.split()
        company_first_word = name_words[0].lower() if name_words else ""
        if (
            lead.company_name.lower() not in invite_low
            and (not company_first_word or company_first_word not in invite_low)
        ):
            issues.append("LinkedIn invite does not mention the company name")

        # 4. ScyllaDB must be mentioned
        if "scylladb" not in invite_low and "scylla" not in invite_low:
            issues.append("LinkedIn invite doesn't mention ScyllaDB")

        # 5. Email subject must exist
        if not lead.follow_up_email_subject or len(lead.follow_up_email_subject) < self.EMAIL_SUBJECT_MIN:
            issues.append("Email subject is missing or too short")

        # 6. Email body minimum length
        if len(email_body) < self.EMAIL_BODY_MIN_LEN:
            issues.append(f"Email body too short ({len(email_body)} chars, min {self.EMAIL_BODY_MIN_LEN})")

        lead.qa_issues = issues
        lead.qa_passed = len(issues) == 0

        if issues:
            self.log.warning(
                f"   ⚠️  {lead.name}: {len(issues)} issue(s) — {'; '.join(issues)}"
            )
        else:
            self.log.info(f"   ✅ {lead.name}: QA passed")
